import { Inter } from "next/font/google";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { ChakraProvider } from "@chakra-ui/react";
import { StoreProvider } from "@/lib/Provider";
import { ThemeProvider } from "@mui/material/styles";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import theme from "@/lib/Themes/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Builder.io",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <ChakraProvider>
            <NextUIProvider>{children}</NextUIProvider>
          </ChakraProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
